version: '3.8'

services: 
  frontend:
    container_name: frontend
    restart: unless-stopped

    build:
      context: .
      dockerfile: ./Dockerfile

    ports: 
      - "3000:3000"

    networks: 
      - wedive-api_default
      - default

networks:
  wedive-api_default:
    external: true