version: '3.8'

services: 
  frontend:
    container_name: frontend
    restart: unless-stopped

    env_file: 
      - /wedive-secret/frontend-config.env

    build:
      context: .
      dockerfile: ./Dockerfile
      args:
         - VUE_APP_API_PATH

    ports: 
      - "3000:3000"

    networks: 
      - wedive-api_default
      - default

    volumes:
      - /wedive-secret:/wedive-secret

networks:
  wedive-api_default:
    external: true